# Generated by Django 4.2.1 on 2023-06-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('anons', models.CharField(max_length=256, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Текст саттьи')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
